# [START rethinkdb client]
apiVersion: v1
kind: Service
metadata:
    name: rethinkdb-ui
    namespace: rethinkdb
spec:
  type: NodePort
  selector:
    app: rethinkdb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: ui
# [END rethinkdb client]
