# [START rethinkdb client]
kind: Service
  apiVersion: v1
  metadata:
    name: rethinkdb-ui
    namespace: rethinkdb
  spec:
    type: NodePort
    selector:
      app: rethinkdb
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
        name: ui
# [END rethinkdb client]
# [START rethinkdb_connection]
---
kind: Service
  apiVersion: v1
  metadata:
    name: rethinkdb-connection
    namespace: rethinkdb
  spec:
    selector:
      app: rethinkdb
    ports:
      - protocol: TCP
        port: 28015
        targetPort: 28015
        name: connection
# [END rethinkdb_connection]