apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # Pod Definition
  name: rethinkdb-pod
  namespace: rethinkdb
  # Labels Definition
  labels:
    purpose: cluster
spec:
  #Containers Definition
  containers:
    # Image Definition
  - name: lates
    image: rethinkdb
    # Networking Definition
    ports:
    - containerPort: 8080
    - containerPort: 28015
    # Health Check
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 2
      failureThreshold: 5
    # Memory/Volume Definition
    volumeMounts:
    - name: rethinkdb-storage
      mountPath: /data/rethink_data
  # Volumes Definition
  volumes:
  - name: rethinkdb-storage
    gcePersistentDisk:
          pdName: rethinkdb-storage-disk
          fsType: ext4